- name: Setup App and Restart PM2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USERNAME }}
    key: ${{ secrets.VPS_SSH_KEY }}
    port: ${{ secrets.VPS_PORT }}
    script: |
      cd /var/www/me-ia-backend

      echo "${{ secrets.ENV_PRODUCTION }}" > .env

      pnpm install --prod --frozen-lockfile

      pm2 reload ecosystem.config.js --update-env || pm2 start ecosystem.config.js

      pm2 save